openapi: 3.0.0
info:   
  version: 1.0.0   
  title: Back End Coursework
  description: matching shelter dogs with new owners and arranging visits.
  contact:     
    name: Lee Wing Yan
    email: 237026594@stu.vtc.edu.hk
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
servers:   
  - url: 'https://8c4e32b2-83e4-4a02-9e2b-aa58c192b5c7-00-3hiyko9zeyulu.sisko.replit.dev:3000/'     
    description: full-stack web app 
tags:
  - name: Users
    description: Prospective owners and the charity 
  - name: Dogs
    description: current dogs available at their physical site
paths:
  /dogs/{id}:
    parameters:
      - in: path
        name: id
        schema: 
          type: integer
        required: true
        description: Numeric id of the dog
    get:
      tags:
        - Dogs
      description:
        get dog by id
      responses:
        '200':
          description: View of adog record
        '404':
          description: Dog not found
    put:
      tags:
        - Dogs
      description:
        update the dog by id
      responses:
        '201':
          description: Update Successfully
        '404':
          description: Dog not found
    delete:
      tags:
        - Dogs
      description:
        Delete dog by ID.
      responses:
        '200':
          description: View of adog record.
        '404':
          description: Dog was not found in the DB.
  /dogs:
    get:
     tags:
     - Dogs
     description: Get all dogs
     responses:
      '200':
       description: OK
      '404':
       description: Not Found  
    post:
      tags:
        - Dogs
      description:
        Create adog
      requestBody:
        description: Dog in JSON format
        required: true
        content:
          application/json:
            schema: 
              $ref: ./dog.json#/definitions/dog
      responses:
        '201':
          description: adog added